grokonez:
    app:
        jwtExpiration: 86400
        jwtSecret: jwtErotemeSecretKey
eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://localhost:9091/eureka/
server:
  port: 8092
spring:
    application:
        name: api-gateway
zuul:
    routes:
        user-authentication-service:
          url: http://localhost:8084
        sensitiveHeaders:
